services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306
    volumes:
      - data:/var/lib/mysql

  employee:
    build:  .
    image: employee:latest
    ports:
      - 8090:8080


  employee-leaves:
    build: .
    image: employee-leaves:latest
    ports:
      - 9090:8080
      
  eureka:
    build: .
    image: discovery-server:latest
    ports:
      - 8762:8761
      
  proxy:
    build: .
    image: proxy-service:latest
    ports:
      - 9006:9005